public enum ClientState
{
    NOT_CONNECTED,
    CLOSING_CONNECTION,
    CLOSED_CONNECTION,
    CONNECTED,
    ASSIGNED,
    REGISTRATION_INFO_SENT,
    LOGIN_INFO_SENT,
    REGISTRATION_ACCEPTED,
    LOGIN_ACCEPTED,
    LOGIN_CHOSEN,
    REGISTRATION_CHOSEN,
    MOVING_TO_DASHBOARD,
}