public enum ClientStates
{
    NOT_CONNECTED,
    CLOSING_CONNECTION,
    CLOSED_CONNECTION,
    CONNECTED,
    ASSIGNED,
    CHOOSING_AUTHENTICATION_METHOD,
    REGISTRATION_INFO_SENT,
    LOGIN_INFO_SENT,
    REGISTRATION_ACCEPTED,
    LOGIN_ACCEPTED,
}